[project]
name = "Halftone"
version = "0.7.0"
requires-python = ">=3.11"

[tool.pyright]
venvPath = "."
venv = "venv"
reportAttributeAccessIssue = false  # Attributes aren't available for Gtk.TemplateChild objects
reportMissingModuleSource = false
